'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:2.0.50727.5420
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    '類別透過 ResGen 或 Visual Studio 這類工具。
    '若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    '(利用 /str 選項)，或重建您的 VS 專案。
    '''<summary>
    '''  用於查詢當地語系化字串等的強型別資源類別
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  傳回這個類別使用的快取的 ResourceManager 執行個體。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LFERP.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        '''  使用這個強型別資源類別的資源查閱。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _123() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("123", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Acheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Acheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Acommon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Acommon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AdvancedFileProperties() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AdvancedFileProperties", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ainform() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ainform", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Areply() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Areply", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Areply1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Areply1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Aurgency() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aurgency", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BarcodeInsert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BarcodeInsert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BlogManageAccounts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlogManageAccounts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BlogPublishMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlogPublishMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chinaz14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chinaz14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ContactSendMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ContactSendMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property editmsg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editmsg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folder_documents_blue_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder-documents-blue-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ForwardInForwardMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ForwardInForwardMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GroupAppointmentOptions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupAppointmentOptions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GroupAttendeesMeetingNotSent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupAttendeesMeetingNotSent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GroupFormulaAuditing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupFormulaAuditing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InviteAttendees() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InviteAttendees", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property letter_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MailMergeGoToFirstRecord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MailMergeGoToFirstRecord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MailMergeGoToNextRecord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MailMergeGoToNextRecord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MailMergeGoToPreviousRecord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MailMergeGoToPreviousRecord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MailMergeGotToLastRecord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MailMergeGotToLastRecord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NetByte_Design_Studio___0745() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NetByte Design Studio - 0745", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NetByte_Design_Studio___0805() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NetByte Design Studio - 0805", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewMailMessage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewMailMessage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property newSendToMailRecipient() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newSendToMailRecipient", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OutlineDemote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutlineDemote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OutlineDemoteToBodyText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutlineDemoteToBodyText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OutlinePromote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutlinePromote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OutlinePromoteToHeading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutlinePromoteToHeading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OutlineSettings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutlineSettings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OutlineShowLevel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutlineShowLevel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PivotExportToExcel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PivotExportToExcel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PivotFilterBySelection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PivotFilterBySelection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PrintDialogAccess() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintDialogAccess", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property QueryAppend() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QueryAppend", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property QueryDelete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QueryDelete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Recurrence() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Recurrence", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Repeat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Repeat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Reply() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reply", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Reply1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reply1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ReplyAll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReplyAll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ReviseContents() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReviseContents", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SaveAndClose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveAndClose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SendItem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SendItem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SharingOpenMailFolder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SharingOpenMailFolder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SharingRequestAllow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SharingRequestAllow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SharingRequestDeny() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SharingRequestDeny", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignatureLineInsertMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignatureLineInsertMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SlideBackgroundReset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SlideBackgroundReset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmartArtChangeColorsGallery() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmartArtChangeColorsGallery", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmartArtDemote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmartArtDemote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmartArtEditIn2D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmartArtEditIn2D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmartArtLayoutGallery() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmartArtLayoutGallery", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmartArtOrganizationChartRightHanging() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmartArtOrganizationChartRightHanging", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmartArtPromote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmartArtPromote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmartArtRightToLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmartArtRightToLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Summer_Collection_005() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Summer_Collection_005", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ZoomClassic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomClassic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
