'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.18444
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LFERP.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _123() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("123", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Acheck() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Acheck", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Acommon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Acommon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AdvancedFileProperties() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AdvancedFileProperties", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ainform() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ainform", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Areply() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Areply", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Areply1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Areply1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Aurgency() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aurgency", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BarcodeInsert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BarcodeInsert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BlogManageAccounts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlogManageAccounts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BlogPublishMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlogPublishMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chinaz14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chinaz14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ContactSendMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ContactSendMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property editmsg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editmsg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder_documents_blue_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder-documents-blue-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ForwardInForwardMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ForwardInForwardMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GroupAppointmentOptions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupAppointmentOptions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GroupAttendeesMeetingNotSent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupAttendeesMeetingNotSent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GroupFormulaAuditing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GroupFormulaAuditing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property InviteAttendees() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InviteAttendees", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property letter_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("letter_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MailMergeGoToFirstRecord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MailMergeGoToFirstRecord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MailMergeGoToNextRecord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MailMergeGoToNextRecord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MailMergeGoToPreviousRecord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MailMergeGoToPreviousRecord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MailMergeGotToLastRecord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MailMergeGotToLastRecord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NetByte_Design_Studio___0745() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NetByte Design Studio - 0745", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NetByte_Design_Studio___0805() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NetByte Design Studio - 0805", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NewMailMessage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewMailMessage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property newSendToMailRecipient() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newSendToMailRecipient", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OutlineDemote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutlineDemote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OutlineDemoteToBodyText() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutlineDemoteToBodyText", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OutlinePromote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutlinePromote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OutlinePromoteToHeading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutlinePromoteToHeading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OutlineSettings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutlineSettings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OutlineShowLevel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OutlineShowLevel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PivotExportToExcel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PivotExportToExcel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PivotFilterBySelection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PivotFilterBySelection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PrintDialogAccess() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintDialogAccess", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property QueryAppend() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QueryAppend", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property QueryDelete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QueryDelete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Recurrence() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Recurrence", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Repeat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Repeat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Reply() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reply", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Reply1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reply1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ReplyAll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReplyAll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ReviseContents() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReviseContents", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SaveAndClose() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveAndClose", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property search_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SendItem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SendItem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SharingOpenMailFolder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SharingOpenMailFolder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SharingRequestAllow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SharingRequestAllow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SharingRequestDeny() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SharingRequestDeny", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SignatureLineInsertMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignatureLineInsertMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SlideBackgroundReset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SlideBackgroundReset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SmartArtChangeColorsGallery() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmartArtChangeColorsGallery", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SmartArtDemote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmartArtDemote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SmartArtEditIn2D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmartArtEditIn2D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SmartArtLayoutGallery() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmartArtLayoutGallery", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SmartArtOrganizationChartRightHanging() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmartArtOrganizationChartRightHanging", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SmartArtPromote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmartArtPromote", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SmartArtRightToLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmartArtRightToLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Summer_Collection_005() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Summer_Collection_005", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ZoomClassic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ZoomClassic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
